<?php
$data = array (
  0 => 
  array (
    'cat_id' => '9',
    'cat_name' => '情报',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '34',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'キーワード',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '36',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '総合案内',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '5',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '4',
    'cat_name' => '会社概要',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '1',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'お買い物ガイド',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '2',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '4',
  ),
  5 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'よくある質問',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => 'よくある質問',
    'sort_order' => '3',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'ご利用規約',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => 'ご利用規約',
    'sort_order' => '4',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'お問い合わせ',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '5',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '1',
  ),
  8 => 
  array (
    'cat_id' => '107',
    'cat_name' => 'カルティエ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '5699',
  ),
  9 => 
  array (
    'cat_id' => '118',
    'cat_name' => 'ジミー・チュウ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '667',
  ),
  10 => 
  array (
    'cat_id' => '129',
    'cat_name' => 'ステラ・マッカートニー',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '548',
  ),
  11 => 
  array (
    'cat_id' => '108',
    'cat_name' => 'セリーヌ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1535',
  ),
  12 => 
  array (
    'cat_id' => '119',
    'cat_name' => 'ランセル',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '286',
  ),
  13 => 
  array (
    'cat_id' => '130',
    'cat_name' => 'トーマス・ワイルド',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '658',
  ),
  14 => 
  array (
    'cat_id' => '109',
    'cat_name' => 'シャネル',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '6028',
  ),
  15 => 
  array (
    'cat_id' => '120',
    'cat_name' => 'ロエベ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1307',
  ),
  16 => 
  array (
    'cat_id' => '131',
    'cat_name' => 'トッズ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '6606',
  ),
  17 => 
  array (
    'cat_id' => '110',
    'cat_name' => 'クロエ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '557',
  ),
  18 => 
  array (
    'cat_id' => '121',
    'cat_name' => 'ルイ・ヴィトン',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '7026',
  ),
  19 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'バレンチノ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1357',
  ),
  20 => 
  array (
    'cat_id' => '111',
    'cat_name' => 'コーチ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '576',
  ),
  21 => 
  array (
    'cat_id' => '122',
    'cat_name' => 'マーク・ジェイコブス',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1877',
  ),
  22 => 
  array (
    'cat_id' => '101',
    'cat_name' => '3.1フィリップリム',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '2809',
  ),
  23 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'イヴ・サンローラン',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '583',
  ),
  24 => 
  array (
    'cat_id' => '112',
    'cat_name' => 'ディオール',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1857',
  ),
  25 => 
  array (
    'cat_id' => '123',
    'cat_name' => 'ミュウミュウ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '983',
  ),
  26 => 
  array (
    'cat_id' => '102',
    'cat_name' => 'アレキサンダー・ワン',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1030',
  ),
  27 => 
  array (
    'cat_id' => '134',
    'cat_name' => 'その他',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '22273',
  ),
  28 => 
  array (
    'cat_id' => '113',
    'cat_name' => 'ドルチェ&ガッバーナ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1451',
  ),
  29 => 
  array (
    'cat_id' => '124',
    'cat_name' => 'マルベリー',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '211',
  ),
  30 => 
  array (
    'cat_id' => '103',
    'cat_name' => 'バレンシアガ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '575',
  ),
  31 => 
  array (
    'cat_id' => '114',
    'cat_name' => 'フェンディ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '627',
  ),
  32 => 
  array (
    'cat_id' => '125',
    'cat_name' => 'プラダ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '5263',
  ),
  33 => 
  array (
    'cat_id' => '104',
    'cat_name' => 'ボッテガ・ヴェネタ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1036',
  ),
  34 => 
  array (
    'cat_id' => '115',
    'cat_name' => 'ジバンシー',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1477',
  ),
  35 => 
  array (
    'cat_id' => '126',
    'cat_name' => 'プロエンザスクーラー',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '115',
  ),
  36 => 
  array (
    'cat_id' => '105',
    'cat_name' => 'バーバリー',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '2014',
  ),
  37 => 
  array (
    'cat_id' => '116',
    'cat_name' => 'グッチ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '4946',
  ),
  38 => 
  array (
    'cat_id' => '127',
    'cat_name' => 'サルヴァトーレ・フェラガモ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '2955',
  ),
  39 => 
  array (
    'cat_id' => '106',
    'cat_name' => 'ブルガリ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '196',
  ),
  40 => 
  array (
    'cat_id' => '117',
    'cat_name' => 'エルメス',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '6234',
  ),
  41 => 
  array (
    'cat_id' => '128',
    'cat_name' => 'サマンサタバサ',
    'cat_type' => '1',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '9',
    'has_children' => '0',
    'aricle_num' => '1141',
  ),
  42 => 
  array (
    'cat_id' => '218',
    'cat_name' => 'Hermes',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  43 => 
  array (
    'cat_id' => '230',
    'cat_name' => 'Alexander Wang',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '895',
  ),
  44 => 
  array (
    'cat_id' => '241',
    'cat_name' => 'Cartier',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  45 => 
  array (
    'cat_id' => '219',
    'cat_name' => 'bottega veneta',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  46 => 
  array (
    'cat_id' => '231',
    'cat_name' => 'ysl',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  47 => 
  array (
    'cat_id' => '242',
    'cat_name' => 'Bvlgari',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  48 => 
  array (
    'cat_id' => '220',
    'cat_name' => 'burberry',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  49 => 
  array (
    'cat_id' => '232',
    'cat_name' => 'Salvatore Ferragamo',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  50 => 
  array (
    'cat_id' => '243',
    'cat_name' => 'Tods',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '871',
  ),
  51 => 
  array (
    'cat_id' => '221',
    'cat_name' => 'balenciaga',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  52 => 
  array (
    'cat_id' => '233',
    'cat_name' => 'Proenza Schoule',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '155',
  ),
  53 => 
  array (
    'cat_id' => '244',
    'cat_name' => 'loewe',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  54 => 
  array (
    'cat_id' => '222',
    'cat_name' => 'prada',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  55 => 
  array (
    'cat_id' => '234',
    'cat_name' => '3.1 Phillip Lim',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '744',
  ),
  56 => 
  array (
    'cat_id' => '245',
    'cat_name' => 'coach',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  57 => 
  array (
    'cat_id' => '223',
    'cat_name' => 'mulberry',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  58 => 
  array (
    'cat_id' => '235',
    'cat_name' => 'Thomas Wylde',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '22',
  ),
  59 => 
  array (
    'cat_id' => '246',
    'cat_name' => 'Juicy Couture',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '270',
  ),
  60 => 
  array (
    'cat_id' => '224',
    'cat_name' => 'miu miu',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  61 => 
  array (
    'cat_id' => '236',
    'cat_name' => 'Dolce & Gabbana',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  62 => 
  array (
    'cat_id' => '247',
    'cat_name' => 'Armani',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  63 => 
  array (
    'cat_id' => '212',
    'cat_name' => 'louis vuitton',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  64 => 
  array (
    'cat_id' => '225',
    'cat_name' => 'Fendi',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  65 => 
  array (
    'cat_id' => '237',
    'cat_name' => 'Lancel',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '553',
  ),
  66 => 
  array (
    'cat_id' => '272',
    'cat_name' => 'Celine',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  67 => 
  array (
    'cat_id' => '256',
    'cat_name' => 'Valentino',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  68 => 
  array (
    'cat_id' => '227',
    'cat_name' => 'Jimmy choo',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  69 => 
  array (
    'cat_id' => '226',
    'cat_name' => 'Dior',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  70 => 
  array (
    'cat_id' => '238',
    'cat_name' => 'Givenchy',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  71 => 
  array (
    'cat_id' => '216',
    'cat_name' => 'chanel',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  72 => 
  array (
    'cat_id' => '273',
    'cat_name' => '其他类别',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  73 => 
  array (
    'cat_id' => '228',
    'cat_name' => 'chloe',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  74 => 
  array (
    'cat_id' => '239',
    'cat_name' => 'Samantha Thavasa',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  75 => 
  array (
    'cat_id' => '217',
    'cat_name' => 'gucci',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  76 => 
  array (
    'cat_id' => '229',
    'cat_name' => 'marc jacobs',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '1000',
  ),
  77 => 
  array (
    'cat_id' => '240',
    'cat_name' => 'Stella McCartney',
    'cat_type' => '6',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '10',
    'has_children' => '0',
    'aricle_num' => '308',
  ),
);
?>