<?php
$data = array (
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => 'バーバリー',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '389',
    'level' => 0,
    'id' => '5',
    'name' => 'バーバリー',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'ルイ・ヴィトン',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '35',
    'goods_num' => 0,
    'level' => 0,
    'id' => '21',
    'name' => 'ルイ・ヴィトン',
  ),
  101 => 
  array (
    'cat_id' => '101',
    'cat_name' => 'アンティア',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '45',
    'level' => 1,
    'id' => '101',
    'name' => 'アンティア',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => 'モノグラム・ジョークス',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '117',
    'name' => 'モノグラム・ジョークス',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => 'ユタ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 1,
    'id' => '133',
    'name' => 'ユタ',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => 'モノグラム・エデン',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '114',
    'name' => 'モノグラム・エデン',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => 'スティーブン・スプラウス',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '34',
    'level' => 1,
    'id' => '130',
    'name' => 'スティーブン・スプラウス',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => 'モノグラム',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '371',
    'level' => 1,
    'id' => '111',
    'name' => 'モノグラム',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => 'ウォーターカラー',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '127',
    'name' => 'ウォーターカラー',
  ),
  108 => 
  array (
    'cat_id' => '108',
    'cat_name' => 'マヒナ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '90',
    'level' => 1,
    'id' => '108',
    'name' => 'マヒナ',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => 'モノグラム・サビア',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '124',
    'name' => 'モノグラム・サビア',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => 'エピ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '188',
    'level' => 1,
    'id' => '105',
    'name' => 'エピ',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => 'モノグラム・ミロワール',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '121',
    'name' => 'モノグラム・ミロワール',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => 'コスミックブラッサム',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '102',
    'name' => 'コスミックブラッサム',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => 'モノグラム・マカサー',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '118',
    'name' => 'モノグラム・マカサー',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '草間彌生',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '74',
    'level' => 1,
    'id' => '134',
    'name' => '草間彌生',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => 'モノグラム・アンプラント',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 1,
    'id' => '115',
    'name' => 'モノグラム・アンプラント',
  ),
  131 => 
  array (
    'cat_id' => '131',
    'cat_name' => 'スハリ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 1,
    'id' => '131',
    'name' => 'スハリ',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => 'モノグラム・デニム',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '74',
    'level' => 1,
    'id' => '112',
    'name' => 'モノグラム・デニム',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => 'モノグラモフラージュ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '128',
    'name' => 'モノグラモフラージュ',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => 'モノグラム・ブロックス',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '109',
    'name' => 'モノグラム・ブロックス',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => 'モノグラム・スエード',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '125',
    'name' => 'モノグラム・スエード',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => 'エンボスレザー',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '106',
    'name' => 'エンボスレザー',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => 'マルチカラー',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '172',
    'level' => 1,
    'id' => '122',
    'name' => 'マルチカラー',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => 'ダミエ・キャンバス',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '307',
    'level' => 1,
    'id' => '103',
    'name' => 'ダミエ・キャンバス',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => 'モノグラム・ミニ・リン',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '31',
    'level' => 1,
    'id' => '119',
    'name' => 'モノグラム・ミニ・リン',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => 'アイオール・カバ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '100',
    'name' => 'アイオール・カバ',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => 'モノグラム・イディール',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '36',
    'level' => 1,
    'id' => '116',
    'name' => 'モノグラム・イディール',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => 'タイガ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '78',
    'level' => 1,
    'id' => '132',
    'name' => 'タイガ',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => 'モノグラム・エクリプス',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '113',
    'name' => 'モノグラム・エクリプス',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => 'ノマド(Nomade)',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '129',
    'name' => 'ノマド(Nomade)',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => 'モノグラム・ビュル',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '110',
    'name' => 'モノグラム・ビュル',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => 'モノグラム・ヴェルニ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '232',
    'level' => 1,
    'id' => '126',
    'name' => 'モノグラム・ヴェルニ',
  ),
  107 => 
  array (
    'cat_id' => '107',
    'cat_name' => 'ショーコレクション',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '44',
    'level' => 1,
    'id' => '107',
    'name' => 'ショーコレクション',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => 'モノグラム・ペルフォ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '123',
    'name' => 'モノグラム・ペルフォ',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => 'ダミエ・ジェアン',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '46',
    'level' => 1,
    'id' => '104',
    'name' => 'ダミエ・ジェアン',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => 'モノグラム・ミラージュ',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '120',
    'name' => 'モノグラム・ミラージュ',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'アレキサンダー・ワン',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '85',
    'level' => 0,
    'id' => '2',
    'name' => 'アレキサンダー・ワン',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => 'ジミーチュウ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '94',
    'level' => 0,
    'id' => '18',
    'name' => 'ジミーチュウ',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => 'ジバンシー',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 0,
    'id' => '15',
    'name' => 'ジバンシー',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => 'トッズ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 0,
    'id' => '31',
    'name' => 'トッズ',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => 'ディオール',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '294',
    'level' => 0,
    'id' => '12',
    'name' => 'ディオール',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => 'サマンサタバサ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 0,
    'id' => '28',
    'name' => 'サマンサタバサ',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => 'シャネル',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '20',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => 'シャネル',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => 'ミニバッグ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '66',
    'level' => 1,
    'id' => '53',
    'name' => 'ミニバッグ',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => 'ココ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '111',
    'level' => 1,
    'id' => '50',
    'name' => 'ココ',
  ),
  47 => 
  array (
    'cat_id' => '47',
    'cat_name' => 'クラシックフラップ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '584',
    'level' => 1,
    'id' => '47',
    'name' => 'クラシックフラップ',
  ),
  44 => 
  array (
    'cat_id' => '44',
    'cat_name' => 'ボーイシャネル',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '70',
    'level' => 1,
    'id' => '44',
    'name' => 'ボーイシャネル',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '財布',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '315',
    'level' => 1,
    'id' => '60',
    'name' => '財布',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => '2.55リシューフラップ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '230',
    'level' => 1,
    'id' => '41',
    'name' => '2.55リシューフラップ',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => 'ローズコレクション',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '49',
    'level' => 1,
    'id' => '57',
    'name' => 'ローズコレクション',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => 'オリジナルレザー',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '254',
    'level' => 1,
    'id' => '54',
    'name' => 'オリジナルレザー',
  ),
  51 => 
  array (
    'cat_id' => '51',
    'cat_name' => 'Ipad カバー',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '51',
    'name' => 'Ipad カバー',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => 'クラシック',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '279',
    'level' => 1,
    'id' => '48',
    'name' => 'クラシック',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'バブル',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '50',
    'level' => 1,
    'id' => '45',
    'name' => 'バブル',
  ),
  42 => 
  array (
    'cat_id' => '42',
    'cat_name' => '2012ニューシャネル',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '102',
    'level' => 1,
    'id' => '42',
    'name' => '2012ニューシャネル',
  ),
  58 => 
  array (
    'cat_id' => '58',
    'cat_name' => 'ショッピングバッグ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '119',
    'level' => 1,
    'id' => '58',
    'name' => 'ショッピングバッグ',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'その他',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '55',
    'name' => 'その他',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => 'Iphone ケース',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 1,
    'id' => '52',
    'name' => 'Iphone ケース',
  ),
  49 => 
  array (
    'cat_id' => '49',
    'cat_name' => 'クラッチ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
    'level' => 1,
    'id' => '49',
    'name' => 'クラッチ',
  ),
  46 => 
  array (
    'cat_id' => '46',
    'cat_name' => 'カンボン',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '66',
    'level' => 1,
    'id' => '46',
    'name' => 'カンボン',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => 'ボーリング',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 1,
    'id' => '43',
    'name' => 'ボーリング',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => 'バレンタインシリーズ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '41',
    'level' => 1,
    'id' => '59',
    'name' => 'バレンタインシリーズ',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'パリモスクワロマノフ',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '56',
    'name' => 'パリモスクワロマノフ',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'プラダ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '503',
    'level' => 0,
    'id' => '25',
    'name' => 'プラダ',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => 'ブルガリ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '78',
    'level' => 0,
    'id' => '6',
    'name' => 'ブルガリ',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'マーク・ジェイコブス',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 0,
    'id' => '22',
    'name' => 'マーク・ジェイコブス',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'バレンシアガ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '296',
    'level' => 0,
    'id' => '3',
    'name' => 'バレンシアガ',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'ランセル',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '55',
    'level' => 0,
    'id' => '19',
    'name' => 'ランセル',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => 'グッチ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '11',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => 'グッチ',
  ),
  69 => 
  array (
    'cat_id' => '69',
    'cat_name' => 'トートバッグ',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '278',
    'level' => 1,
    'id' => '69',
    'name' => 'トートバッグ',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => 'その他',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 1,
    'id' => '66',
    'name' => 'その他',
  ),
  63 => 
  array (
    'cat_id' => '63',
    'cat_name' => 'コスメティックケース',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 1,
    'id' => '63',
    'name' => 'コスメティックケース',
  ),
  70 => 
  array (
    'cat_id' => '70',
    'cat_name' => 'トラベル',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '70',
    'name' => 'トラベル',
  ),
  67 => 
  array (
    'cat_id' => '67',
    'cat_name' => 'ショルダーバッグ',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '279',
    'level' => 1,
    'id' => '67',
    'name' => 'ショルダーバッグ',
  ),
  64 => 
  array (
    'cat_id' => '64',
    'cat_name' => 'ホーボーバッグ',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '90',
    'level' => 1,
    'id' => '64',
    'name' => 'ホーボーバッグ',
  ),
  61 => 
  array (
    'cat_id' => '61',
    'cat_name' => 'バックパック',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '61',
    'name' => 'バックパック',
  ),
  71 => 
  array (
    'cat_id' => '71',
    'cat_name' => '財布',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '201',
    'level' => 1,
    'id' => '71',
    'name' => '財布',
  ),
  68 => 
  array (
    'cat_id' => '68',
    'cat_name' => 'トップハンドル',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '229',
    'level' => 1,
    'id' => '68',
    'name' => 'トップハンドル',
  ),
  65 => 
  array (
    'cat_id' => '65',
    'cat_name' => 'メッセンジャーバッグ',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '136',
    'level' => 1,
    'id' => '65',
    'name' => 'メッセンジャーバッグ',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => 'クラッチバッグ',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '43',
    'level' => 1,
    'id' => '62',
    'name' => 'クラッチバッグ',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => 'バレンチノ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '32',
    'level' => 0,
    'id' => '32',
    'name' => 'バレンチノ',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'ドルチェ＆ガッバーナ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '34',
    'level' => 0,
    'id' => '13',
    'name' => 'ドルチェ＆ガッバーナ',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => 'ステラ・マッカートニー',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 0,
    'id' => '29',
    'name' => 'ステラ・マッカートニー',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => 'クロエ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '118',
    'level' => 0,
    'id' => '10',
    'name' => 'クロエ',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'プロエンザスクーラー',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 0,
    'id' => '26',
    'name' => 'プロエンザスクーラー',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => 'カルティエ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '28',
    'level' => 0,
    'id' => '7',
    'name' => 'カルティエ',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => 'ミュウミュウ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '167',
    'level' => 0,
    'id' => '23',
    'name' => 'ミュウミュウ',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => 'ボッテガ・ヴェネタ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '258',
    'level' => 0,
    'id' => '4',
    'name' => 'ボッテガ・ヴェネタ',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'ロエベ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 0,
    'id' => '20',
    'name' => 'ロエベ',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '3.1フィリップリム',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 0,
    'id' => '1',
    'name' => '3.1フィリップリム',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'エルメス',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '28',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => 'エルメス',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'ラージレザーH',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '85',
    'name' => 'ラージレザーH',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => 'エールバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '29',
    'level' => 1,
    'id' => '82',
    'name' => 'エールバッグ',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => 'ツールボックス',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '98',
    'name' => 'ツールボックス',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => 'Feu2Dou',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '79',
    'name' => 'Feu2Dou',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => 'ソーケリー',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '68',
    'level' => 1,
    'id' => '95',
    'name' => 'ソーケリー',
  ),
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => 'クラッチ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '72',
    'level' => 1,
    'id' => '76',
    'name' => 'クラッチ',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => 'ピコタン',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '92',
    'name' => 'ピコタン',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'ボリード',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 1,
    'id' => '73',
    'name' => 'ボリード',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '他のバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '157',
    'level' => 1,
    'id' => '89',
    'name' => '他のバッグ',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => 'リンディ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
    'level' => 1,
    'id' => '86',
    'name' => 'リンディ',
  ),
  83 => 
  array (
    'cat_id' => '83',
    'cat_name' => 'ジプシエール',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '26',
    'level' => 1,
    'id' => '83',
    'name' => 'ジプシエール',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '財布',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '225',
    'level' => 1,
    'id' => '99',
    'name' => '財布',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'ガーデンパーティ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 1,
    'id' => '80',
    'name' => 'ガーデンパーティ',
  ),
  96 => 
  array (
    'cat_id' => '96',
    'cat_name' => 'スティーヴ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '96',
    'name' => 'スティーヴ',
  ),
  77 => 
  array (
    'cat_id' => '77',
    'cat_name' => 'コンスタンス',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '100',
    'level' => 1,
    'id' => '77',
    'name' => 'コンスタンス',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => 'ルーリーバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '93',
    'name' => 'ルーリーバッグ',
  ),
  74 => 
  array (
    'cat_id' => '74',
    'cat_name' => 'ボーリング',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '74',
    'name' => 'ボーリング',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'その他',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '90',
    'name' => 'その他',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'メドールバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '87',
    'name' => 'メドールバッグ',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => 'ケリー',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '185',
    'level' => 1,
    'id' => '84',
    'name' => 'ケリー',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => 'グッドニュースH',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '81',
    'name' => 'グッドニュースH',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => 'スティラップバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '54',
    'level' => 1,
    'id' => '97',
    'name' => 'スティラップバッグ',
  ),
  78 => 
  array (
    'cat_id' => '78',
    'cat_name' => 'エヴリン',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 1,
    'id' => '78',
    'name' => 'エヴリン',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => 'ショッピングバッグ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '94',
    'name' => 'ショッピングバッグ',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'ブリーフケース',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '75',
    'name' => 'ブリーフケース',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'パリボンベイ',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '91',
    'name' => 'パリボンベイ',
  ),
  72 => 
  array (
    'cat_id' => '72',
    'cat_name' => 'バーキン',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '406',
    'level' => 1,
    'id' => '72',
    'name' => 'バーキン',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => 'オリジナルレザー',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '185',
    'level' => 1,
    'id' => '88',
    'name' => 'オリジナルレザー',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => 'イヴ・サンローラン',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '46',
    'level' => 0,
    'id' => '33',
    'name' => 'イヴ・サンローラン',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => 'フェンディ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '337',
    'level' => 0,
    'id' => '14',
    'name' => 'フェンディ',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => 'トーマス・ワイルド',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '45',
    'level' => 0,
    'id' => '30',
    'name' => 'トーマス・ワイルド',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => 'コーチ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 0,
    'id' => '11',
    'name' => 'コーチ',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => 'サルヴァトーレ・フェラガモ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 0,
    'id' => '27',
    'name' => 'サルヴァトーレ・フェラガモ',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => 'セリーヌ',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '8',
    'name' => 'セリーヌ',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => 'ファントム',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '63',
    'level' => 1,
    'id' => '37',
    'name' => 'ファントム',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => 'カバ',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 1,
    'id' => '34',
    'name' => 'カバ',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => 'トラペーズ',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '65',
    'level' => 1,
    'id' => '38',
    'name' => 'トラペーズ',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => 'ドクターフレーム',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '35',
    'name' => 'ドクターフレーム',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => 'クラスプバッグ',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '39',
    'name' => 'クラスプバッグ',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '財布',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '135',
    'name' => '財布',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => 'ラゲージ',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '214',
    'level' => 1,
    'id' => '36',
    'name' => 'ラゲージ',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '他のバッグ',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '71',
    'level' => 1,
    'id' => '40',
    'name' => '他のバッグ',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => 'マルベリー',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '50',
    'level' => 0,
    'id' => '24',
    'name' => 'マルベリー',
  ),
);
?>